# Generated by Django 4.2.23 on 2026-09-27 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('permiso', 'Permiso'), ('certificado', 'Certificado'), ('resolucion', 'Resolucion'), ('seguro', 'Seguro'), ('otro', 'Otro')], default='otro', max_length=12)),
                ('tipo_detalle', models.CharField(blank=True, max_length=100)),
                ('entidad_emisora', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('sin_vigencia', 'Sin vigencia registrada'), ('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido')], db_index=True, default='sin_vigencia', max_length=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento legal',
                'verbose_name_plural': 'Documentos legales',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/%Y/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='documental.documentolegal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de documento',
                'verbose_name_plural': 'Versiones de documento',
                'ordering': ['documento', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentolegal',
            constraint=models.CheckConstraint(check=models.Q(('fecha_emision__isnull', True), ('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', models.F('fecha_emision')), _connector='OR'), name='documentolegal_vencimiento_posterior_a_emision'),
        ),
        migrations.AddConstraint(
            model_name='versiondocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'version'), name='versiondocumento_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='versiondocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('documento',), name='versiondocumento_una_vigente_por_documento'),
        ),
    ]
