# Generated by Django 4.2.23 on 2026-09-08 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual de compost'), ('semanal', 'Semanal por material'), ('comercial', 'Rendimiento comercial')], max_length=10)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('supuestos', models.JSONField(default=dict, help_text='Copia de los parametros usados al calcular (volumen, densidad, factor, sacos/m3, precio). CU-54 edita esta copia sin tocar la config global.')),
                ('valor_proyectado', models.JSONField(default=dict, help_text='Resultado del calculo (toneladas/m3/sacos/ingreso).')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, help_text='Solo en proyecciones por material (semanal); nulo en las agregadas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecciones', to='mantenedores.material')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyeccion',
                'verbose_name_plural': 'Proyecciones',
                'ordering': ['-fecha_generada'],
            },
        ),
    ]
