# Generated by Django 4.2.23 on 2026-09-07 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('chip_estimado_kg', models.FloatField()),
                ('compost_estimado_kg', models.FloatField()),
                ('chip_real_kg', models.FloatField(blank=True, null=True)),
                ('compost_real_kg', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proyecciones_semanales',
                'ordering': ['-semana'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7, unique=True)),
                ('chip_estimado_kg', models.FloatField()),
                ('compost_estimado_kg', models.FloatField()),
                ('chip_real_kg', models.FloatField(blank=True, null=True)),
                ('compost_real_kg', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proyecciones_mensuales',
                'ordering': ['-mes'],
            },
        ),
    ]
