graph TD
    A[Gerencia General] --> B(Javier - Product Owner / Socio Técnico);
    A --> C(José - Socio de Operaciones);
    A --> D(Área Comercial y Administrativa);

    C --> E(Jefe de Planta);
    E --> F(Operador de Planta 1);
    E --> G(Operador de Planta 2);

    D --> H(Encargado de Ventas);
    D --> I(Encargado de Administración);

    style A fill:#f9f,stroke:#333,stroke-width:4px,color:black
    style B fill:#bbf,stroke:#333,color:black
    style C fill:#bbf,stroke:#333,color:black
    style D fill:#bbf,stroke:#333,color:black
    style E fill:#ddf,stroke:#333,color:black
    style F fill:#eef,stroke:#333,color:black
    style G fill:#eef,stroke:#333,color:black
    style H fill:#eef,stroke:#333,color:black
    style I fill:#eef,stroke:#333,color:black
