graph TD
    A[Junta de Socios - Triverde SpA] --> B(Javier Acosta<br/>Socio - Area Tecnica y Administrativa)
    A --> C(Jose Trivelli<br/>Socio - Area Operativa y Comercial)
    B -.-> D[Ayudantes esporadicos]
    C -.-> D
    C -.-> E[Servicios externos<br/>maquinaria con operador]

    style A fill:#f9f,stroke:#333,stroke-width:4px,color:black
    style B fill:#bbf,stroke:#333,color:black
    style C fill:#bbf,stroke:#333,color:black
    style D fill:#eef,stroke:#333,color:black
    style E fill:#eef,stroke:#333,color:black
