# Generated by Django 4.2.23 on 2026-08-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Parametro de conversion',
                'verbose_name_plural': 'Parametros de conversion',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='TarifaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo_min_m3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tramo_max_m3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa de recepcion',
                'verbose_name_plural': 'Tarifas de recepcion',
                'ordering': ['tramo_min_m3'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambioParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_nuevo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='configuracion.parametroconversion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_parametro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de parametro',
                'verbose_name_plural': 'Historial de cambios de parametro',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
