# Generated by Django 4.2.23 on 2026-09-08 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostoOperativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("litro", "Litro"),
                            ("hora", "Hora"),
                            ("dia", "Dia"),
                            ("viaje", "Viaje"),
                            ("unidad", "Unidad"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vigente", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Costo operativo",
                "verbose_name_plural": "Costos operativos",
                "ordering": ["concepto"],
            },
        ),
        migrations.CreateModel(
            name="CostoTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("costo_por_km", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vigente", models.BooleanField(default=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Costo de transporte",
                "verbose_name_plural": "Costos de transporte",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RecetaMezcla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("relacion_seca", models.DecimalField(decimal_places=2, max_digits=6)),
                ("relacion_verde", models.DecimalField(decimal_places=2, max_digits=6)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("vigente", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Receta de mezcla",
                "verbose_name_plural": "Recetas de mezcla",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="recetamezcla",
            constraint=models.CheckConstraint(
                check=models.Q(("relacion_seca__gt", 0)), name="receta_seca_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="recetamezcla",
            constraint=models.CheckConstraint(
                check=models.Q(("relacion_verde__gt", 0)), name="receta_verde_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="costotransporte",
            constraint=models.CheckConstraint(
                check=models.Q(("costo_por_km__gt", 0)), name="costo_km_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="costotransporte",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigente", True)),
                fields=("vigente",),
                name="costo_km_solo_un_vigente",
            ),
        ),
        migrations.AddConstraint(
            model_name="costooperativo",
            constraint=models.CheckConstraint(
                check=models.Q(("monto__gt", 0)), name="costo_operativo_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="costooperativo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigente", True)),
                fields=("concepto",),
                name="costo_operativo_concepto_unico_vigente",
            ),
        ),
    ]
