# Generated by Django 4.2.23 on 2026-09-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('mezcla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha_generada', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='alerta',
            name='alerta_activa_origen_clave_unica',
        ),
        migrations.AddField(
            model_name='alerta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('seca', 'Seca'), ('verde', 'Verde')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='disponible_m3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='faltante_m3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='pila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.pila'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='clave',
            field=models.CharField(blank=True, help_text='Identificador estable para no duplicar alertas. Ejemplos: mantencion:15 o mezcla:pila:8:seca.', max_length=160),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa'), models.Q(('clave', ''), _negated=True)), fields=('origen', 'clave'), name='alerta_activa_origen_clave_unica'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa'), ('origen', 'mezcla')), fields=('pila', 'categoria'), name='alerta_mezcla_activa_pila_categoria_unica'),
        ),
    ]
