# Generated by Django 4.2.23 on 2026-09-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0001_initial'),
        ('mezcla', '0002_mezcla_campos_y_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='documental.documentolegal'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa'), ('origen', 'documento')), fields=('documento',), name='alerta_documento_activa_unica'),
        ),
    ]
