# Generated by Django 4.2.23 on 2026-09-28 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicadores_visibles', models.JSONField(default=list)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_control', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
