# Generated by Django 4.2.23 on 2026-08-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_pago', models.CharField(choices=[('al dia', 'Al dia'), ('con deuda', 'Con deuda')], default='al dia', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('categoria', models.CharField(blank=True, choices=[('seca', 'Seca'), ('verde', 'Verde')], help_text='Seca/verde. Pendiente de confirmar con Javier.', max_length=6, null=True)),
                ('densidad_kg_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('factor_reduccion_chip', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('admite_chip', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('chip', 'Chip'), ('mulch', 'Mulch'), ('compost', 'Compost'), ('lena', 'Lena')], max_length=10)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_de_venta', models.CharField(choices=[('saco', 'Saco'), ('m3', 'Metro cubico')], max_length=6)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('capacidad_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tramo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('estado_operativo', models.CharField(choices=[('operativa', 'Operativa'), ('en mantencion', 'En mantencion'), ('fuera de servicio', 'Fuera de servicio')], default='operativa', max_length=17)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='mantenedores.cliente')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportistas', to='mantenedores.cliente')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'ordering': ['nombre'],
            },
        ),
    ]
