# Generated by Django 4.2.23 on 2026-09-01 23:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('en formacion', 'En formacion'), ('en proceso', 'En proceso'), ('en reposo', 'En reposo'), ('cerrada', 'Cerrada')], default='en formacion', max_length=16)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pila',
                'verbose_name_plural': 'Pilas',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoPila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave alterna generada en el dispositivo; idempotencia de sync (CU-33).', unique=True)),
                ('estado_sincronizacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizada', 'Sincronizada'), ('en conflicto', 'En conflicto')], default='pendiente', max_length=12)),
                ('tipo', models.CharField(choices=[('triturado', 'Triturado'), ('volteo', 'Volteo'), ('riego', 'Riego'), ('harneado', 'Harneado'), ('reposo', 'Reposo'), ('ensacado', 'Ensacado')], max_length=16)),
                ('fecha', models.DateTimeField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('chip_pendiente', models.BooleanField(default=False, help_text='Triturado sin factor de reduccion configurado (CU-37 Excepcion 3).')),
                ('advertencia', models.CharField(blank=True, help_text='Observacion del sistema, p. ej. temperatura sobre el techo (CU-38 Excepcion 2).', max_length=200, null=True)),
                ('material', models.ForeignKey(blank=True, help_text='Solo en el triturado (CU-37); el resto lo deduce de la pila.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_pila', to='mantenedores.material')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_registrados', to=settings.AUTH_USER_MODEL)),
                ('pila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='inventario.pila')),
            ],
            options={
                'verbose_name': 'Proceso de pila',
                'verbose_name_plural': 'Procesos de pila',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('por triturar', 'Por triturar'), ('chip', 'Chip'), ('pila en proceso', 'Pila en proceso'), ('curado', 'Curado'), ('ensacado', 'Ensacado')], max_length=20)),
                ('volumen_m3', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='mantenedores.material')),
            ],
            options={
                'verbose_name': 'Existencia de inventario',
                'verbose_name_plural': 'Inventario',
                'ordering': ['material__nombre', 'etapa'],
            },
        ),
        migrations.CreateModel(
            name='ComposicionPila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones_pila', to='mantenedores.material')),
                ('pila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composiciones', to='inventario.pila')),
            ],
            options={
                'verbose_name': 'Composicion de pila',
                'verbose_name_plural': 'Composicion de pilas',
                'ordering': ['pila', 'material'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('material', 'etapa'), name='inventario_unico_material_etapa'),
        ),
        migrations.AddConstraint(
            model_name='composicionpila',
            constraint=models.UniqueConstraint(fields=('pila', 'material'), name='composicionpila_unica_por_material'),
        ),
    ]
