# Generated by Django 4.2.23 on 2026-09-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AporteRecepcionPila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes_pila', to='recepcion.detallerecepcion')),
                ('pila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='inventario.pila')),
            ],
            options={
                'verbose_name': 'Aporte de recepcion a pila',
                'verbose_name_plural': 'Aportes de recepcion a pila',
                'ordering': ['pila', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='aporterecepcionpila',
            constraint=models.UniqueConstraint(fields=('pila', 'detalle_recepcion'), name='aporte_unico_por_pila_y_detalle'),
        ),
    ]
