# Generated by Django 4.2.23 on 2026-08-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave alterna generada en el dispositivo; idempotencia de sync (CU-33).', unique=True)),
                ('estado_sincronizacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizada', 'Sincronizada'), ('en conflicto', 'En conflicto')], default='pendiente', max_length=12)),
                ('conductor', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('en curso', 'En curso'), ('pendiente de inspeccion', 'Pendiente de inspeccion'), ('recibida', 'Recibida'), ('rechazada', 'Rechazada')], default='en curso', max_length=24)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='mantenedores.cliente')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_operadas', to=settings.AUTH_USER_MODEL)),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='mantenedores.transportista')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='mantenedores.vehiculo')),
            ],
            options={
                'verbose_name': 'Recepcion',
                'verbose_name_plural': 'Recepciones',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave alterna generada en el dispositivo; idempotencia de sync (CU-33).', unique=True)),
                ('estado_sincronizacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizada', 'Sincronizada'), ('en conflicto', 'En conflicto')], default='pendiente', max_length=12)),
                ('motivo', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='mantenedores.cliente')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='recepcion.recepcion')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave alterna generada en el dispositivo; idempotencia de sync (CU-33).', unique=True)),
                ('estado_sincronizacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizada', 'Sincronizada'), ('en conflicto', 'En conflicto')], default='pendiente', max_length=12)),
                ('archivo', models.ImageField(upload_to='recepciones/%Y/%m/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='recepcion.recepcion')),
            ],
            options={
                'verbose_name': 'Foto de recepcion',
                'verbose_name_plural': 'Fotos de recepcion',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave alterna generada en el dispositivo; idempotencia de sync (CU-33).', unique=True)),
                ('estado_sincronizacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizada', 'Sincronizada'), ('en conflicto', 'En conflicto')], default='pendiente', max_length=12)),
                ('volumen_m3', models.DecimalField(decimal_places=2, help_text='Unico dato tecleado; no hay balanza (R2).', max_digits=8)),
                ('peso_derivado_kg', models.DecimalField(decimal_places=2, help_text='Derivado (volumen x densidad) y persistido como hecho historico (docs/11 Decision 1).', max_digits=10)),
                ('chip_derivado_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('destino_sugerido', models.CharField(blank=True, choices=[('a pila', 'A pila'), ('a chip', 'A chip'), ('a venta directa', 'A venta directa')], max_length=16, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recepcion', to='mantenedores.material')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recepcion.recepcion')),
            ],
            options={
                'verbose_name': 'Detalle de recepcion',
                'verbose_name_plural': 'Detalles de recepcion',
            },
        ),
    ]
