# Generated by Django 4.2.23 on 2026-09-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("recepcion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("recepcion", "Recepcion"), ("pila", "Pila")],
                        max_length=10,
                    ),
                ),
                (
                    "co2_evitado_kg",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("metodo", models.CharField(max_length=200)),
                ("fecha", models.DateField(db_index=True)),
                (
                    "pila",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicadores_ambientales",
                        to="inventario.pila",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicadores_ambientales",
                        to="recepcion.recepcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador ambiental",
                "verbose_name_plural": "Indicadores ambientales",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="indicadorambiental",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        ("origen", "recepcion"),
                        ("pila__isnull", True),
                        ("recepcion__isnull", False),
                    )
                    | models.Q(
                        ("origen", "pila"),
                        ("pila__isnull", False),
                        ("recepcion__isnull", True),
                    )
                ),
                name="indicador_ambiental_origen_excluyente",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicadorambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recepcion__isnull", False)),
                fields=("recepcion",),
                name="indicador_ambiental_recepcion_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicadorambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pila__isnull", False)),
                fields=("pila",),
                name="indicador_ambiental_pila_unica",
            ),
        ),
    ]

