# Generated by Django 4.2.23 on 2026-09-25 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0002_vehiculo_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0001_initial'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionSinader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='sinader/')),
                ('contenido', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaraciones_sinader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Declaracion SINADER',
                'verbose_name_plural': 'Declaraciones SINADER',
                'ordering': ['-fecha_generada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('descarga', 'Descarga'), ('consolidado', 'Consolidado')], max_length=11)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('contenido', models.JSONField(default=dict)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_trazabilidad', to='mantenedores.cliente')),
                ('recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_trazabilidad', to='recepcion.recepcion')),
            ],
            options={
                'verbose_name': 'Certificado de trazabilidad',
                'verbose_name_plural': 'Certificados de trazabilidad',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificadotrazabilidad',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('periodo_fin__isnull', True), ('periodo_inicio__isnull', True), ('recepcion__isnull', False), ('tipo', 'descarga')), models.Q(('periodo_fin__isnull', False), ('periodo_inicio__isnull', False), ('recepcion__isnull', True), ('tipo', 'consolidado')), _connector='OR'), name='certificado_tipo_coherente'),
        ),
    ]
